language: python

jobs:
  include:
    - python: 3.8

before_install:
- pip install poetry

install:
  - poetry install
  - pip install poetry
  - pip install "pytest >= 3.7.2"


script:
  - poetry run pytest tests

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.net#8banana"
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
